version: '3.8'

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: estoque_livros
      MYSQL_PASSWORD: root123
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_INITDB_SKIP_TZINFO: "yes"

  api:
    image: app_livro
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/estoque_livros
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123